//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmanHoldingSirket
    {
        public int DepartmanHoldingSirketId { get; set; }
        public int DepartmanId { get; set; }
        public int SirketId { get; set; }
    
        public virtual Departmanlar Departmanlar { get; set; }
        public virtual Sirketler Sirketler { get; set; }
    }
}
