//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departmanlar
    {
        public Departmanlar()
        {
            this.DepartmanHoldingSirket = new HashSet<DepartmanHoldingSirket>();
            this.Zimmet = new HashSet<Zimmet>();
        }
    
        public int DepartmanId { get; set; }
        public string DepartmanAdi { get; set; }
    
        public virtual ICollection<DepartmanHoldingSirket> DepartmanHoldingSirket { get; set; }
        public virtual ICollection<Zimmet> Zimmet { get; set; }
    }
}
