//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holdingler
    {
        public Holdingler()
        {
            this.Sirketler = new HashSet<Sirketler>();
        }
    
        public int HoldingId { get; set; }
        public string HoldingAdi { get; set; }
    
        public virtual ICollection<Sirketler> Sirketler { get; set; }
    }
}
