//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KisiDepartman
    {
        public int KisiId { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public int DepartmanId { get; set; }
        public string DepartmanAdi { get; set; }
    }
}
