//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sirketler
    {
        public Sirketler()
        {
            this.DepartmanHoldingSirket = new HashSet<DepartmanHoldingSirket>();
        }
    
        public int SirketId { get; set; }
        public int HoldingId { get; set; }
        public string SirketAdi { get; set; }
    
        public virtual ICollection<DepartmanHoldingSirket> DepartmanHoldingSirket { get; set; }
        public virtual Holdingler Holdingler { get; set; }
    }
}
