//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        public Urun()
        {
            this.Demirbas = new HashSet<Demirbas>();
            this.Urun_Stok = new HashSet<Urun_Stok>();
        }
    
        public int UrunId { get; set; }
        public int KategoriId { get; set; }
        public string UrunAdi { get; set; }
        public decimal UrunBirimFiyati { get; set; }
        public Nullable<System.DateTime> SatinAlinmaTarihi { get; set; }
        public Nullable<bool> Silindi { get; set; }
    
        public virtual ICollection<Demirbas> Demirbas { get; set; }
        public virtual Kategori Kategori { get; set; }
        public virtual ICollection<Urun_Stok> Urun_Stok { get; set; }
    }
}
