//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip1.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    //using System.Data.Objects;
    //using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class YaSinamaEntities : DbContext
    {
        public YaSinamaEntities()
            : base("name=YaSinamaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Demirbas> Demirbas { get; set; }
        public DbSet<Demirbas_Departman> Demirbas_Departman { get; set; }
        public DbSet<DepartmanHoldingSirket> DepartmanHoldingSirket { get; set; }
        public DbSet<Departmanlar> Departmanlar { get; set; }
        public DbSet<Holdingler> Holdingler { get; set; }
        public DbSet<Kategori> Kategori { get; set; }
        public DbSet<Kisi> Kisi { get; set; }
        public DbSet<Kullanici> Kullanici { get; set; }
        public DbSet<Kullanici_Role> Kullanici_Role { get; set; }
        public DbSet<Roller> Roller { get; set; }
        public DbSet<Sirketler> Sirketler { get; set; }
        public DbSet<Urun> Urun { get; set; }
        public DbSet<Urun_Stok> Urun_Stok { get; set; }
        public DbSet<Zimmet> Zimmet { get; set; }
        public DbSet<KisiDepartman> KisiDepartman { get; set; }
    
        public virtual int sp_DemirbasDuzenle(Nullable<int> demirbasNo, Nullable<int> holdingId, Nullable<int> sirketId, Nullable<int> kategoriId, Nullable<int> demirbasAdedi, string demirbasAciklama)
        {
            var demirbasNoParameter = demirbasNo.HasValue ?
                new ObjectParameter("demirbasNo", demirbasNo) :
                new ObjectParameter("demirbasNo", typeof(int));
    
            var holdingIdParameter = holdingId.HasValue ?
                new ObjectParameter("holdingId", holdingId) :
                new ObjectParameter("holdingId", typeof(int));
    
            var sirketIdParameter = sirketId.HasValue ?
                new ObjectParameter("sirketId", sirketId) :
                new ObjectParameter("sirketId", typeof(int));
    
            var kategoriIdParameter = kategoriId.HasValue ?
                new ObjectParameter("kategoriId", kategoriId) :
                new ObjectParameter("kategoriId", typeof(int));
    
            var demirbasAdediParameter = demirbasAdedi.HasValue ?
                new ObjectParameter("demirbasAdedi", demirbasAdedi) :
                new ObjectParameter("demirbasAdedi", typeof(int));
    
            var demirbasAciklamaParameter = demirbasAciklama != null ?
                new ObjectParameter("demirbasAciklama", demirbasAciklama) :
                new ObjectParameter("demirbasAciklama", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DemirbasDuzenle", demirbasNoParameter, holdingIdParameter, sirketIdParameter, kategoriIdParameter, demirbasAdediParameter, demirbasAciklamaParameter);
        }
    
        public virtual int sp_DemirbasEkle(Nullable<int> holdingId, Nullable<int> sirketId, Nullable<int> kategoriId, Nullable<int> urunId, Nullable<int> demirbasAdedi, string demirbasAciklama)
        {
            var holdingIdParameter = holdingId.HasValue ?
                new ObjectParameter("holdingId", holdingId) :
                new ObjectParameter("holdingId", typeof(int));
    
            var sirketIdParameter = sirketId.HasValue ?
                new ObjectParameter("sirketId", sirketId) :
                new ObjectParameter("sirketId", typeof(int));
    
            var kategoriIdParameter = kategoriId.HasValue ?
                new ObjectParameter("kategoriId", kategoriId) :
                new ObjectParameter("kategoriId", typeof(int));
    
            var urunIdParameter = urunId.HasValue ?
                new ObjectParameter("urunId", urunId) :
                new ObjectParameter("urunId", typeof(int));
    
            var demirbasAdediParameter = demirbasAdedi.HasValue ?
                new ObjectParameter("demirbasAdedi", demirbasAdedi) :
                new ObjectParameter("demirbasAdedi", typeof(int));
    
            var demirbasAciklamaParameter = demirbasAciklama != null ?
                new ObjectParameter("demirbasAciklama", demirbasAciklama) :
                new ObjectParameter("demirbasAciklama", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DemirbasEkle", holdingIdParameter, sirketIdParameter, kategoriIdParameter, urunIdParameter, demirbasAdediParameter, demirbasAciklamaParameter);
        }
    
        public virtual int sp_Departmandaki_Demirbas01(Nullable<int> departmanId)
        {
            var departmanIdParameter = departmanId.HasValue ?
                new ObjectParameter("DepartmanId", departmanId) :
                new ObjectParameter("DepartmanId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Departmandaki_Demirbas01", departmanIdParameter);
        }
    
        public virtual int sp_Departmandaki_Demirbas02(Nullable<int> departmanId)
        {
            var departmanIdParameter = departmanId.HasValue ?
                new ObjectParameter("DepartmanId", departmanId) :
                new ObjectParameter("DepartmanId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Departmandaki_Demirbas02", departmanIdParameter);
        }
    
        public virtual int sp_DepartmanDemirbasEkle(Nullable<int> demirbasId, Nullable<int> departmanId, Nullable<int> adet)
        {
            var demirbasIdParameter = demirbasId.HasValue ?
                new ObjectParameter("DemirbasId", demirbasId) :
                new ObjectParameter("DemirbasId", typeof(int));
    
            var departmanIdParameter = departmanId.HasValue ?
                new ObjectParameter("DepartmanId", departmanId) :
                new ObjectParameter("DepartmanId", typeof(int));
    
            var adetParameter = adet.HasValue ?
                new ObjectParameter("Adet", adet) :
                new ObjectParameter("Adet", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DepartmanDemirbasEkle", demirbasIdParameter, departmanIdParameter, adetParameter);
        }
    
        public virtual int sp_DepartmanEkle(string departmanAdi, Nullable<int> sirketId)
        {
            var departmanAdiParameter = departmanAdi != null ?
                new ObjectParameter("DepartmanAdi", departmanAdi) :
                new ObjectParameter("DepartmanAdi", typeof(string));
    
            var sirketIdParameter = sirketId.HasValue ?
                new ObjectParameter("SirketId", sirketId) :
                new ObjectParameter("SirketId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DepartmanEkle", departmanAdiParameter, sirketIdParameter);
        }
    
        public virtual int sp_DepartmanGuncelle(Nullable<int> departmanId, string departmanAdi, Nullable<int> sirketId, Nullable<int> kisiId)
        {
            var departmanIdParameter = departmanId.HasValue ?
                new ObjectParameter("DepartmanId", departmanId) :
                new ObjectParameter("DepartmanId", typeof(int));
    
            var departmanAdiParameter = departmanAdi != null ?
                new ObjectParameter("DepartmanAdi", departmanAdi) :
                new ObjectParameter("DepartmanAdi", typeof(string));
    
            var sirketIdParameter = sirketId.HasValue ?
                new ObjectParameter("SirketId", sirketId) :
                new ObjectParameter("SirketId", typeof(int));
    
            var kisiIdParameter = kisiId.HasValue ?
                new ObjectParameter("KisiId", kisiId) :
                new ObjectParameter("KisiId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DepartmanGuncelle", departmanIdParameter, departmanAdiParameter, sirketIdParameter, kisiIdParameter);
        }
    
        public virtual int sp_kisi_Demirbas(Nullable<int> kisiId)
        {
            var kisiIdParameter = kisiId.HasValue ?
                new ObjectParameter("kisiId", kisiId) :
                new ObjectParameter("kisiId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_kisi_Demirbas", kisiIdParameter);
        }
    
        public virtual int sp_kisi_Demirbas1(Nullable<int> kisiId)
        {
            var kisiIdParameter = kisiId.HasValue ?
                new ObjectParameter("kisiId", kisiId) :
                new ObjectParameter("kisiId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_kisi_Demirbas1", kisiIdParameter);
        }
    
        public virtual int sp_UrunEkle(Nullable<int> kategoriId, string urunAdi, Nullable<decimal> urunBirimFiyati, Nullable<int> stok, Nullable<System.DateTime> satinAlinmaTarihi)
        {
            var kategoriIdParameter = kategoriId.HasValue ?
                new ObjectParameter("KategoriId", kategoriId) :
                new ObjectParameter("KategoriId", typeof(int));
    
            var urunAdiParameter = urunAdi != null ?
                new ObjectParameter("UrunAdi", urunAdi) :
                new ObjectParameter("UrunAdi", typeof(string));
    
            var urunBirimFiyatiParameter = urunBirimFiyati.HasValue ?
                new ObjectParameter("UrunBirimFiyati", urunBirimFiyati) :
                new ObjectParameter("UrunBirimFiyati", typeof(decimal));
    
            var stokParameter = stok.HasValue ?
                new ObjectParameter("Stok", stok) :
                new ObjectParameter("Stok", typeof(int));
    
            var satinAlinmaTarihiParameter = satinAlinmaTarihi.HasValue ?
                new ObjectParameter("SatinAlinmaTarihi", satinAlinmaTarihi) :
                new ObjectParameter("SatinAlinmaTarihi", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UrunEkle", kategoriIdParameter, urunAdiParameter, urunBirimFiyatiParameter, stokParameter, satinAlinmaTarihiParameter);
        }
    
        public virtual int sp_UrunGuncelle(Nullable<int> urunId, Nullable<int> kategoriId, string urunAdi, Nullable<decimal> urunBirimFiyati, Nullable<int> stok, Nullable<System.DateTime> satinAlinmaTarihi)
        {
            var urunIdParameter = urunId.HasValue ?
                new ObjectParameter("UrunId", urunId) :
                new ObjectParameter("UrunId", typeof(int));
    
            var kategoriIdParameter = kategoriId.HasValue ?
                new ObjectParameter("KategoriId", kategoriId) :
                new ObjectParameter("KategoriId", typeof(int));
    
            var urunAdiParameter = urunAdi != null ?
                new ObjectParameter("UrunAdi", urunAdi) :
                new ObjectParameter("UrunAdi", typeof(string));
    
            var urunBirimFiyatiParameter = urunBirimFiyati.HasValue ?
                new ObjectParameter("UrunBirimFiyati", urunBirimFiyati) :
                new ObjectParameter("UrunBirimFiyati", typeof(decimal));
    
            var stokParameter = stok.HasValue ?
                new ObjectParameter("Stok", stok) :
                new ObjectParameter("Stok", typeof(int));
    
            var satinAlinmaTarihiParameter = satinAlinmaTarihi.HasValue ?
                new ObjectParameter("SatinAlinmaTarihi", satinAlinmaTarihi) :
                new ObjectParameter("SatinAlinmaTarihi", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UrunGuncelle", urunIdParameter, kategoriIdParameter, urunAdiParameter, urunBirimFiyatiParameter, stokParameter, satinAlinmaTarihiParameter);
        }
    }
}
