//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakip1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zimmet
    {
        public Zimmet()
        {
            this.Demirbas_Departman = new HashSet<Demirbas_Departman>();
        }
    
        public int ZimmetId { get; set; }
        public Nullable<int> KisiId { get; set; }
        public Nullable<int> DepartmanId { get; set; }
    
        public virtual ICollection<Demirbas_Departman> Demirbas_Departman { get; set; }
        public virtual Departmanlar Departmanlar { get; set; }
        public virtual Kisi Kisi { get; set; }
    }
}
